name: Submission Package Bug
description: 'Report a bug found in a submission package'
title: "Submission Package bug - "
labels: bug, submission_package
assignees: 'chris-s-friedman'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!
  - type: textarea
    id: description
    attributes: 
      label: Describe the bug
      description: A clear and concise description of what the bug is.
  - type: textarea
    id: expectation
    attributes: 
      label: Expected behavior
      description: A clear and concise description of what you expected the data to look like.
  - type: dropdown
    id: release
    attributes:
      label: Version ID
      description: Select the version number relating to this bug
      options: # new_versions_here
        - "0.10.0"
        - "0.9.0"
        - "0.8.1"
        - "0.8.0"
        - "0.7.1"
        - "0.7.0"
        - "0.6.0"
        - "0.5.3"
        - "0.5.2"
        - "0.5.0"
        - "0.4.0"
        - "0.3.0"
        - "0.2.0"
        - "0.1.0"
  - type: checkboxes
    id: effected_files
    attributes: 
      label: Effected file(s)
      description: Select the file(s) relating to this bug
      options: 
        - label: sample
        - label: participant
        - label: diagnosis
        - label: diagnosis_sample_mapping
        - label: file
        - label: file_sample_participant_map
        - label: genomic_info
