---
name: Lint Code Base
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    name: Lint New Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}


      - name: Lint Code Base
        uses: github/super-linter@latest
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: false
          VALIDATE_GITHUB_ACTIONS: false
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
          LINTER_RULES_PATH: /